// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laoswserfgdmwessnjyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhb3N3c2VyZmdkbXdlc3Nuanl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzgwMDUsImV4cCI6MjA1ODYxNDAwNX0.noitVYHfwbtyivnnfy4HaKl0GNVDysCoIo_oYSlx1_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);